export const promptOptions = {
  gender: ["Male", "Female"],
  ethnicity: [
    "Caucasian",
    "Black",
    "Asian",
    "Latino",
    "Middle Eastern",
    "South Asian",
    "Mixed",
  ],
  skin_tone: ["Fair", "Light", "Medium", "Olive", "Tan", "Brown", "Dark"],
  hair_color: [
    "Black",
    "Brown",
    "Blonde",
    "Red",
    "Gray",
    "White",
    "Pink",
    "Blue",
    "Purple",
  ],
  hair_style: [
    "Short Straight",
    "Short Curly",
    "Medium Straight",
    "Medium Wavy",
    "Long Straight",
    "Long Wavy",
    "Afro",
    "Bald",
    "Ponytail",
    "Bun",
    "Braids",
  ],
  facial_hair: ["None", "Mustache", "Beard", "Goatee", "Stubble"],
  pose: [
    "Front-facing neutral",
    "Three-quarter turn",
    "Side profile",
    "Back view",
    "Walking pose",
    "One hand on hip",
    "Hands in pockets",
    "Arms crossed",
  ],
  body_type: ["Slim", "Athletic", "Average", "Plus-size", "Petite", "Tall"],
  age: ["Teen", "Young Adult", "Adult", "Middle-aged", "Senior"],
  expression: ["Neutral", "Soft smile", "Confident", "Happy", "Serious"],
  hand_position: [
    "At sides",
    "One hand on hip",
    "Both hands on hips",
    "Hands in pockets",
    "Arms crossed",
    "One arm relaxed, one raised",
  ],
  pose_level: ["Full-body", "Three-quarter length", "Half-body", "Headshot"],
  camera_perspective: ["Front", "Three-quarter", "Side", "Back"],
  background: [
    "White",
    "Light gray",
    "Transparent",
    "Lifestyle room",
    "Studio gradient",
  ],
};

export type PromptOptionsKey = keyof typeof promptOptions;
